global_scale = 0.4000000059604645
anchor_name = "bottom_left"
font = "futura-book-bt.ttf"
font_size = 40.0
# The size of the hud, in pixels. Will be scaled.
size = { x = 800.0, y = 800.0 }

# Only draw the ammo slot when a weapon that uses ammo (ranged) is equipped.
hide_ammo_when_irrelevant = true
# Hide the left hand slot when a ranged weapon is equipped. This lets you
# use the same location as the left hand to show ammo.
hide_left_when_irrelevant = true

chinese_full_glyphs = false
simplified_chinese_glyphs = false
cyrillic_glyphs = false
japanese_glyphs = false
korean_glyphs = false
thai_glyphs = false
vietnamese_glyphs = false

# ---------- BACKGROUND
# An optional background image. If your layout doesn't have an overall background, you
# can safely leave this out. All background elements look like this.
[background]
# This is the file name of an SVG that must be in resources/backgrounds.
# You can supply a different image with your layout and either overwrite the default
# image or give it a new name that you use here.
svg = "hud_bg.svg"
# The size to draw the image. Is scaled, so it'll be multiplied by 0.4
size = { x = 800.0, y = 800.0 }
# The color to use to draw this slot's background. Alpha of 0 means it's not visible.
# Color is expressed as RGBA; values are 0-255.
color = { r = 0, g = 0, b = 0, a = 64 }

# ---------- SHOUTS & POWERS
[power]

# The offset of the center of this slot relative to the center of the HUD.
# This gets scaled when the global scaling factor is applied.
offset = { x = -230.0, y = -230.0 }

# Optional slot background image: if not present, not drawn. You can have
# different background images for different slots if you like. The background
# is always drawn in the exact center of the slot.
[power.background]
# This is the image drawn in the background. It can be different for
# every slot.
svg = "slot_bg.svg"
# Size of this background image, before scaling.
size = { x = 300.0 , y = 300.0 }
# Color to use to draw the background image. While it will be invisible
# if you set the alpha to 0, it's better to omit this section entirely if
# you don't want to draw a background image.
color = { r = 255, g = 255, b = 255, a = 128 }

# The icon element of this slot. This element is *not* optional.
[power.icon]
# Color for this HUD's icon. Alpha of 0 means it's not drawn. The icon is
# always centered in the slot.
color = { r = 200, g = 200, b = 200, a = 255 }
# Size of the icon for this slot, before scaling.
size = { x = 175.0, y = 175.0 }
# Where to draw the icon, relative to the center of the slot.
offset = { x = 0.0, y = 0.0 }

# Optional display for the slot's hotkey.
[power.hotkey]
# Size before scaling.
size = { x = 60.0, y = 60.0 }
# Where to draw the hotkey. Gets scaled.
offset = { x = 190.0, y = 0.0 }
# color for drawing the hotkey's image
color = { r = 255, g = 255, b = 255, a = 255 }
# An optional background image for the hotkey. You can leave this out to not
# draw a background for the hotkey display. For this layout, we don't draw it.
#[power.hotkey.background]
#svg = "hotkey_bg.svg"
#size = { x = 30.0 , y = 30.0}
#color = { r = 255, g = 255, b = 255, a = 128 }

# An array of text elements for this slot. You can have as many
# as you want, but each one costs time to draw so use them wisely.
# The text can include values filled in from the item's info.
# (TOML hint: double square brackets around a category means you can
# have more than one of them.)
[[power.text]]
offset = { x = 0.0, y = 160.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
font_size = 50.0
# How to align name and count text for this text element.
# IMPORTANT DOCUMENTATION! The options are left, right, center.
# Text alignment is, for cognitive ease reasons, also a statement about
# where the stated anchor point is.
# Center alignment: the offset refers to the center of the text box.
# Left alignment: the offset refers to the center of the left edge.
# Right alignment: the offset refers to the center of the right edge.
alignment = "center"
# The contents of the text to draw. This can be fixed text, e.g.,
#     contents = "Hello, world!"
# or it can substitute in values from the item shown in the slot.
# To fill in a value, use it with curly braces, like this
# example, which draws the name of the item shown. You can use more
# than one.
# Possible values: count, name, kind,
contents = "{name}"

# ---------- UTILITIES AND CONSUMABLES
# The consumables slot. You can change all of these values
# independently from the other slots.
[utility]
offset = { x = 230.0, y = -230.0 }

[utility.background]
size = { x = 300.0 , y = 300.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
svg = "slot_bg.svg"

[utility.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 175.0, y = 175.0 }
offset = { x = 0.0, y = 0.0 }

[utility.hotkey]
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = -190.0, y = 0.0 }
size = { x = 60.0, y = 60.0 }

[[utility.text]]
contents = "{count}"
alignment = "center"
font_size = 60.0
offset = { x = 0.0, y = 0.0 }
color = { r = 255, g = 255, b = 255, a = 255 }

[[utility.text]]
contents = "{name}"
alignment = "center"
font_size = 50.0
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 0.0, y = 160.0 }

# ---------- LEFT HAND
[left]
offset = { x = -230.0, y = 230.0 }

[left.background]
size = { x = 300.0 , y = 300.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
svg = "slot_bg.svg"

[left.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 175.0, y = 175.0 }
offset = { x = 0.0, y = 0.0 }

[left.hotkey]
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 190.0, y = 0.0 }
size = { x = 60.0, y = 60.0 }

[[left.text]]
contents = "{name}"
alignment = "center"
font_size = 50.0
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 0.0, y = -210.0 }

# ---------- RIGHT HAND
[right]
offset = { x = 230.0, y = 230.0 }
[right.background]
svg = "slot_bg.svg"
size = { x = 300.0 , y = 300.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
[right.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 175.0, y = 175.0 }
offset = { x = 0.0, y = 0.0 }
[right.hotkey]
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = -190.0, y = 0.0 }
size = { x = 60.0, y = 60.0 }
[[right.text]]
contents = "{name}"
alignment = "center"
font_size = 50.0
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 0.0, y = -210.0 }

# ---------- AMMO
# This layout swaps ammo in for the left hand when a ranged
# weapon is equipped, so it's in the same position as the left
# hand slot.
[ammo]
offset = { x = -230.0, y = 230.0 }
[ammo.background]
svg = "slot_bg.svg"
size = { x = 300.0 , y = 300.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
[ammo.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 175.0, y = 175.0 }
offset = { x = 0.0, y = 0.0 }
[ammo.hotkey]
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 190.0, y = 0.0 }
size = { x = 60.0, y = 60.0 }
[[ammo.text]]
contents = "{count} {name}"
alignment = "center"
offset = { x = 0.0, y = -210.0 }
font_size = 40.0
color = { r = 255, g = 255, b = 255, a = 255 }
