global_scale = 0.4000000059604645
anchor_name = "top_left"
font = "futura-book-bt.ttf"
font_size = 40.0
# The size of the hud, in pixels. Will be scaled.
size = { x = 800.0, y = 800.0 }

# The color of the HUD background file. Set alpha to 0 to skip drawing a background.
bg_color = { r = 0, g = 0, b = 0, a = 64 }
# Only draw the ammo slot when a weapon that uses ammo (ranged) is equipped.
hide_ammo_when_irrelevant = true
# Hide the left hand slot when a ranged weapon is equipped. This lets you
# use the same location as the left hand to show ammo.
hide_left_when_irrelevant = true

chinese_full_glyphs = false
simplified_chinese_glyphs = false
cyrillic_glyphs = false
japanese_glyphs = false
korean_glyphs = false
thai_glyphs = false
vietnamese_glyphs = false

# ---------- SHOUTS & POWERS
[power]
# The offset of the center of this slot relative to the center of the HUD.
# This gets scaled when the global scaling factor is applied.
offset = { x = -230.0, y = -230.0 }

[power.background]
# This is the image drawn in the background. It can be different for
# every slot.
svg = "slot_bg.svg"
# Size of this slot, before scaling.
size = { x = 300.0 , y = 300.0 }
# The color to use to draw this slot's background. Alpha of 0 means it's not visible.
# Color is expressed as RGBA; values are 0-255.
color = { r = 255, g = 255, b = 255, a = 128 }

[power.icon]
# The icon element of this slot. This element is *not* optional.
# Color for this HUD's icon. Alpha of 0 means it's not drawn. The icon is
# always centered in the slot.
color = { r = 200, g = 200, b = 200, a = 255 }
# Size of the icon for this slot, before scaling.
size = { x = 175.0, y = 175.0 }
# Where to draw the icon, relative to the center of the slot.
offset = { x = 0.0, y = 0.0 }

[power.hotkey]
# Color for this HUD's hotkey. Alpha of 0 means it's not drawn.
color = { r = 255, g = 255, b = 255, a = 255 }
# Where to draw the hotkey. Gets scaled.
offset = { x = 190.0, y = 0.0 }
# Size of the hotkey. Also scaled.
size = { x = 60.0, y = 60.0 }

[[power.text]]
alignment = "center"
offset = { x = 0.0, y = 160.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
font_size = 50.0
contents = "{name}"

# ---------- UTILITIES AND CONSUMABLES
# The consumables slot. You can change all of these values
# independently from the other slots.
[utility]
offset = { x = 230.0, y = -230.0 }

[utility.background]
size = { x = 300.0 , y = 300.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
svg = "slot_bg.svg"

[utility.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 175.0, y = 175.0 }
offset = { x = 0.0, y = 0.0 }

[utility.hotkey]
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = -190.0, y = 0.0 }
size = { x = 60.0, y = 60.0 }

[[utility.text]]
contents = "{count}"
alignment = "center"
font_size = 60.0
offset = { x = 0.0, y = 0.0 }
color = { r = 255, g = 255, b = 255, a = 255 }

[[utility.text]]
contents = "{name}"
alignment = "center"
font_size = 50.0
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 0.0, y = 160.0 }

# ---------- LEFT HAND
[left]
offset = { x = -230.0, y = 230.0 }

[left.background]
size = { x = 300.0 , y = 300.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
svg = "slot_bg.svg"

[left.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 175.0, y = 175.0 }
offset = { x = 0.0, y = 0.0 }

[left.hotkey]
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 190.0, y = 0.0 }
size = { x = 60.0, y = 60.0 }

[[left.text]]
contents = "{name}"
alignment = "center"
font_size = 50.0
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 0.0, y = -210.0 }

# ---------- RIGHT HAND
[right]
offset = { x = 230.0, y = 230.0 }
[right.background]
svg = "slot_bg.svg"
size = { x = 300.0 , y = 300.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
[right.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 175.0, y = 175.0 }
offset = { x = 0.0, y = 0.0 }
[right.hotkey]
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = -190.0, y = 0.0 }
size = { x = 60.0, y = 60.0 }
[[right.text]]
contents = "{name}"
alignment = "center"
font_size = 50.0
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 0.0, y = -210.0 }

# ---------- AMMO
# This layout swaps ammo in for the left hand when a ranged
# weapon is equipped, so it's in the same position as the left
# hand slot.
[ammo]
offset = { x = -230.0, y = 230.0 }
[ammo.background]
svg = "slot_bg.svg"
size = { x = 300.0 , y = 300.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
[ammo.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 175.0, y = 175.0 }
offset = { x = 0.0, y = 0.0 }
[ammo.hotkey]
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = 190.0, y = 0.0 }
size = { x = 60.0, y = 60.0 }
[[ammo.text]]
contents = "{count} {name}"
alignment = "center"
offset = { x = 0.0, y = -210.0 }
font_size = 40.0
color = { r = 255, g = 255, b = 255, a = 255 }
