global_scale = 1.0
anchor_name = "bottom_left"
# anchor = { x = 2100.0, y = 825.0 }

# Only draw the ammo slot when a weapon that uses ammo (ranged) is equipped.
hide_ammo_when_irrelevant = true
# Hide the left hand slot when a ranged weapon is equipped. This lets you
# use the same location as the left hand to show ammo.
hide_left_when_irrelevant = true

# Typeface to use. Must be truetype. Must be in resources/fonts.
font = "futura-book-bt.ttf"
# A font sizing hint to the font loader about what size most of the text will use.
# Text rendered at this size will look best. This value is scaled before the font is loaded.
# Text alignment calculations are made using this font size.
font_size = 18.0

# Enable any of these you need text rendering for.
# You will need to supply a true-type font with the glyphs; futura doesn't have them.
# The "Inter" font packaged with the i18 layout does have them.
chinese_full_glyphs = false
simplified_chinese_glyphs = false
cyrillic_glyphs = false
japanese_glyphs = false
korean_glyphs = false
thai_glyphs = false
vietnamese_glyphs = false

# Optional background image. All image elements look like this.
[background]
svg = "hud_bg.svg"
size = { x = 300.0 , y = 300.0}
color = { r = 255, g = 255, b = 255, a = 128 }

# ----- right hand slot

# The slot showing what's in the right hand.
[right]
# Where the center of this element is relative to the HUD anchor.
offset = { x = 375.0, y = 0.0 }

# Optional slot background image: if not present, not drawn
[right.background]
svg = "right_bg.svg"
size = { x = 100.0 , y = 100.0}
color = { r = 255, g = 255, b = 255, a = 128 }

# Optional icon: if not present, not drawn. Color might be overridden if
# the user has "colorize icons" enabled.
[right.icon]
size = { x = 60.0, y = 60.0 }
offset = { x = 0.0, y = 0.0 }
color = {r = 200, g = 200, b = 200, a = 255}

# Optional display for the slot's hotkey. All hotkey elements look like this.
[right.hotkey]
size = { x = 30.0, y = 30.0 }
offset = { x = -50.0, y = 0.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
# optional background image for the hotkey. If not present, not drawn.
[right.hotkey.background]
svg = "hotkey_bg.svg"
size = { x = 30.0 , y = 30.0}
color = { r = 255, g = 255, b = 255, a = 128 }

# Each of these is a different text element.
# Text data: count, name, ??
[[right.text]]
alignment = "right"
offset = { x = 0.0, y = 0.0 }
color = { r = 255, g = 255, b = 255, a = 0 }
font_size = 18.0
format = "{count}"

[[right.text]]
alignment = "left"
offset = { x = -50.0, y = 55.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
font_size = 18.0
format = "{name}"

# Optional burn time/enchant charge bar. NOT YET IMPLEMENTED.
[right.progress_bar]
offset = { x = 20.0, y = 20.0 }
background = "bar_bg.svg"
color = { r = 255, g = 255, b = 255, a = 255 }
size = { x = 10.0 , y = 100.0 } # this is
orientation = "horizontal" # defaults to vertical

# ----- left hand slot

[left]
offset = { x = 250.0, y = 0.0 }

[left.background]
svg = "left_bg.svg"
size = { x = 100.0 , y = 100.0}
color = { r = 255, g = 255, b = 255, a = 128 }

[left.icon]
size = { x = 60.0, y = 60.0 }
offset = { x = 0.0, y=0.0 }
color = {r = 200, g = 200, b = 200, a = 255}

[left.hotkey]
size = { x = 30.0, y = 30.0 }
offset = { x = -50.0, y = 0.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
[left.hotkey.background]
svg = "hotkey_bg.svg"
size = { x = 30.0 , y = 30.0}
color = { r = 255, g = 255, b = 255, a = 128 }

[[left.text]]
alignment = "left"
offset = { x = -50.0, y = 55.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
font_size = 18.0
format = "{count} {name}"

# ----- utility slot

[utility]
offset = { x = 125.0, y = 0.0 }
[utility.background]
svg = "slot_bg.svg"
size = { x = 100.0 , y = 100.0}
color = { r = 255, g = 255, b = 255, a = 128 }
[utility.icon]
size = { x = 60.0, y = 60.0 }
offset = { x = 0.0, y=0.0 }
color = {r = 200, g = 200, b = 200, a = 255}
[utility.hotkey]
size = { x = 30.0, y = 30.0 }
offset = { x = -50.0, y = 0.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
[utility.hotkey.background]
svg = "hotkey_bg.svg"
size = { x = 30.0 , y = 30.0}
color = { r = 255, g = 255, b = 255, a = 128 }
[[utility.text]]
alignment = "left"
offset = { x = 15.0, y = 15.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
font_size = 24.0
format = "{count}"
[[utility.text]]
alignment = "left"
offset = { x = -50.0, y = 55.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
font_size = 18.0
format = "{name}"

# ----- power slot

[power]
offset = { x = 0.0, y = 0.0 }
[power.background]
svg = "slot_bg.svg"
size = { x = 100.0 , y = 100.0}
color = { r = 255, g = 255, b = 255, a = 128 }
[power.icon]
size = { x = 60.0, y = 60.0 }
offset = { x = 0.0, y=0.0 }
color = {r = 200, g = 200, b = 200, a = 255}
[power.hotkey]
size = { x = 30.0, y = 30.0 }
offset = { x = -50.0, y = 0.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
[power.hotkey.background]
svg = "hotkey_bg.svg"
size = { x = 30.0 , y = 30.0}
color = { r = 255, g = 255, b = 255, a = 128 }

[[power.text]]
alignment = "center"
offset = { x = 0.0, y = 55.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
font_size = 18.0
format = "{name}"

# ----- ammo slot

[ammo]
offset = { x = 250.0, y = 0.0 }
[ammo.background]
svg = "slot_bg.svg"
size = { x = 100.0 , y = 100.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
[ammo.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 60.0, y = 60.0 }
offset = { x = 0.0, y=0.0 }
[ammo.hotkey]
size = { x = 30.0, y = 30.0 }
offset = { x = -50.0, y = 0.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
[[ammo.text]]
alignment = "left"
format = "{count}"
color = { r = 200, g = 200, b = 200, a = 255 }
font_size = 24.0
offset = { x = 15.0, y = 15.0 }
[[ammo.text]]
alignment = "left"
format = "{name}"
offset = { x = -50, y =  55.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
font_size = 18.0

# ----- equipset slot

[equipset]
align_text = "center"
offset = { x = 0.0, y = -125.0 }
[equipset.background]
svg = "slot_bg.svg"
size = { x = 100.0 , y = 100.0 }
color = { r = 255, g = 255, b = 255, a = 128 }
[equipset.icon]
color = { r = 200, g = 200, b = 200, a = 255 }
size = { x = 60.0, y = 60.0 }
offset = { x = 0.0, y=0.0 }
[equipset.hotkey]
color = { r = 255, g = 255, b = 255, a = 255 }
offset = { x = -50.0, y = 0.0 }
size = { x = 30.0, y = 30.0 }
[[equipset.text]]
format = "{name}"
offset = { x = 0.0, y = -75.0 }
color = { r = 255, g = 255, b = 255, a = 255 }
font_size = 18.0
