# Global scaling factor: the whole hud size changes when you change this.
global_scale = 1.0
# The location of the *center* of the HUD, in pixels offset from the top left
# corner. These numbers do NOT change with the global scale.
anchor = { x = 1620.0, y = 720.0 } # the center of my screen; move to be in the center of yours!
# The size of the hud, before the global scaling factor is applied.
size = { x = 300.0, y = 300.0 }
# The color of the HUD background file. Set alpha to 0 to skip drawing a background.
bg_color = { r = 0, g = 0, b = 0, a = 0 }
# Enable to turn on debug logging. Requires a game restart.
debug = true
# Typeface to use. Must be truetype or otf. Must be in resources/fonts.
font = "Inter-Light.ttf"
# Point size to use for all name text. Scales with the global_scale.
font_size = 20.0
# Enable any of these you need text rendering for. The Inter typeface
# should support all of them.
chinese_full_glyphs = false
simplified_chinese_glyphs = false
cyrillic_glyphs = false
japanese_glyphs = false
korean_glyphs = false
thai_glyphs = false
vietnamese_glyphs = false

# This is the sub-layout for the shouts and powers slot.
[[layouts]]
# This name is to help people figure out which slot they're on. It's not
# drawn in the HUD.
name = "Shouts/Powers"
# How to align name and count text for this slot.
align_text = "left"
# Used to help the hud renderer figure out which slot this is. Complicated
# handwave about serializing TOML.
element = { repr = 0 }
# The offset of the center of this slot relative to the center of the HUD.
# This gets scaled when the global scaling factor is applied.
offset = { x = 325.0, y = 0.0 }
# Size of this slot, before scaling.
size = { x = 100.0, y = 100.0 }
# The color to use to draw this slot's background. Alpha of 0 means it's not visible.
bg_color = { r = 255, g = 255, b = 255, a = 128 }
# Color for this HUD's icon. Alpha of 0 means it's not drawn. The icon is
# always centered in the slot.
icon_color = { r = 200, g = 200, b = 200, a = 255 }
# Size of the icon for this slot, before scaling.
icon_size = { x = 40.0, y = 40.0 }
# Color for this HUD's hotkey. Alpha of 0 means it's not drawn.
hotkey_color = { r = 255, g = 255, b = 255, a = 0 }
# Where to draw the hotkey. Gets scaled.
hotkey_offset = { x = -41.0, y = 41.0 }
# Size of the hotkey. Also scaled.
hotkey_size = { x = 30.0, y = 30.0 }
# Background color. Alpha of 0 means invisible.
hotkey_bg_color = { r = 0, g = 0, b = 0, a = 0 }
# Offset for any count text. Gets scaled.
count_offset = { x = 0.0, y = 0.0 }
# The color for any count displays.
count_color = { r = 255, g = 255, b = 255, a = 0 }
# Not used for this slot, since powers don't have counts.
count_font_size = 15.0
# The color for the name text of any item in this slot.
name_color = { r = 255, g = 255, b = 255, a = 255 }
# Where to draw the item name. Gets scaled.
name_offset = { x = 60.0, y = -13.0 }

[[layouts]]
name = "Consumables"
element = { repr = 1 }
offset = { x = -325.0, y = 0.0 }
size = { x = 100.0, y = 100.0 }
align_text = "right"
bg_color = { r = 255, g = 255, b = 255, a = 128 }
icon_color = { r = 200, g = 200, b = 200, a = 255 }
icon_size = { x = 40.0, y = 40.0 }
hotkey_color = { r = 255, g = 255, b = 255, a = 0 }
hotkey_offset = { x = 41.0, y = -41.0 }
hotkey_size = { x = 30.0, y = 30.0 }
hotkey_bg_color = { r = 0, g = 0, b = 0, a = 0 }
count_offset = { x = 25.0, y = 40.0 }
count_color = { r = 255, g = 255, b = 255, a = 0 }
count_font_size = 20.0
name_color = { r = 255, g = 255, b = 255, a = 255 }
name_offset = { x = -70.0, y = -12.0 }


[[layouts]]
name = "Left Hand"
element = { repr = 2 }
offset = { x = -325.0, y = 200.0 }
size = { x = 100.0, y = 100.0 }
align_text = "left"
bg_color = { r = 255, g = 255, b = 255, a = 128 }
icon_color = { r = 200, g = 200, b = 200, a = 255 }
icon_size = { x = 40.0, y = 40.0 }
hotkey_color = { r = 255, g = 255, b = 255, a = 0 }
hotkey_offset = { x = 41.0, y = 41.0 }
hotkey_size = { x = 30.0, y = 30.0 }
hotkey_bg_color = { r = 0, g = 0, b = 0, a = 0 }
count_offset = { x = 0.0, y = 0.0 }
count_color = { r = 255, g = 255, b = 255, a = 0 }
count_font_size = 20.0
name_color = { r = 255, g = 255, b = 255, a = 255 }
name_offset = { x = -70.0, y = -12.0 }


[[layouts]]
name = "Right Hand"
element = { repr = 3 }
offset = { x = 325.0, y = 200.0 }
size = { x = 100.0, y = 100.0 }
align_text = "left"
bg_color = { r = 255, g = 255, b = 255, a = 128 }
icon_color = { r = 200, g = 200, b = 200, a = 255 }
icon_size = { x = 40.0, y = 40.0 }
hotkey_color = { r = 255, g = 255, b = 255, a = 0 }
hotkey_offset = { x = -41.0, y = -41.0 }
hotkey_size = { x = 30.0, y = 30.0 }
hotkey_bg_color = { r = 0, g = 0, b = 0, a = 0 }
count_offset = { x = 0.0, y = 0.0 }
count_color = { r = 255, g = 255, b = 255, a = 0 }
count_font_size = 20.0
name_color = { r = 255, g = 255, b = 255, a = 255 }
name_offset = { x = 50.0, y = -25.0 }


[[layouts]]
name = "Ammo"
element = { repr = 4 }
count_font_size = 20.0
offset = { x = 325.0, y = 200.0 }
size = { x = 100.0, y = 100.0 }
align_text = "left"
bg_color = { r = 255, g = 255, b = 255, a = 0 }
icon_color = { r = 200, g = 200, b = 200, a = 0 }
icon_size = { x = 35.0, y = 35.0 }
hotkey_color = { r = 255, g = 255, b = 255, a = 0 }
hotkey_offset = { x = 0.0, y = 0.0 }
hotkey_size = { x = 20.0, y = 20.0 }
hotkey_bg_color = { r = 0, g = 0, b = 0, a = 0 }
count_offset = { x = 50.0, y = 5.0 }
count_color = { r = 255, g = 255, b = 255, a = 255 }
name_color = { r = 255, g = 255, b = 255, a = 255 }
name_offset = { x = 75.0, y = 5.0 }
