set(headers ${headers}
    src/PCH.h
    src/config/custom_setting.h
    src/config/file_setting.h
    src/config/user_settings.h
    src/game/equippable.h
    src/game/gear.h
    src/game/magic.h
    src/game/perk_visitor.h
    src/game/player.h
    src/game/utility_items.h
    src/migrate_me/handle/data/ammo_data.h
    src/migrate_me/handle/data/page/position_draw_setting.h
    src/migrate_me/handle/data/page/position_setting.h
    src/migrate_me/handle/data/page/slot_setting.h
    src/migrate_me/handle/extra_data_holder.h
    src/migrate_me/handle/key_position_handle.h
    src/migrate_me/handle/name_handle.h
    src/plugin/hooks.h
    src/plugin/keycodes.h
    src/plugin/papyrus.h
    src/plugin/sinks.h
    src/renderer/animation_handler.h
    src/renderer/image_path.h
    src/renderer/ui_renderer.h
    src/util/config_writer_helper.h
    src/util/constant.h
    src/util/enums.h
    src/util/helpers.h
    src/util/key_path.h
    src/util/offset.h
    src/util/string_util.h
)
set(sources ${sources}
    ${headers}
    src/config/custom_setting.cpp
    src/config/file_setting.cpp
    src/config/user_settings.cpp
    src/game/equippable.cpp
    src/game/gear.cpp
    src/game/magic.cpp
    src/game/perk_visitor.cpp
    src/game/player.cpp
    src/game/utility_items.cpp
    src/main.cpp
    src/migrate_me/handle/extra_data_holder.cpp
    src/migrate_me/handle/key_position_handle.cpp
    src/migrate_me/handle/name_handle.cpp
    src/plugin/hooks.cpp
    src/plugin/keycodes.cpp
    src/plugin/papyrus.cpp
    src/plugin/sinks.cpp
    src/renderer/ui_renderer.cpp
    src/util/helpers.cpp
)
