set(sources ${sources}
	src/PCH.h
	src/control/binding.cpp
	src/control/binding.h
	src/control/common.cpp
	src/control/common.h
	src/equip/equip_slot.cpp
	src/equip/equip_slot.h
	src/equip/item.cpp
	src/equip/item.h
	src/equip/magic.cpp
	src/equip/magic.h
	src/event/equip_event.cpp
	src/event/equip_event.h
	src/event/key_manager.cpp
	src/event/key_manager.h
	src/event/menu_manager.cpp
	src/event/menu_manager.h
	src/event/sink_event.cpp
	src/event/sink_event.h
	src/handle/ammo_handle.cpp
	src/handle/ammo_handle.h
	src/handle/data/ammo_data.h
	src/handle/data/data_helper.h
	src/handle/data/page/position_draw_setting.h
	src/handle/data/page/position_setting.h
	src/handle/data/page/slot_setting.h
	src/handle/extra_data_holder.cpp
	src/handle/extra_data_holder.h
	src/handle/key_position_handle.cpp
	src/handle/key_position_handle.h
	src/handle/name_handle.cpp
	src/handle/name_handle.h
	src/handle/page_handle.cpp
	src/handle/page_handle.h
	src/hook/hook.cpp
	src/hook/hook.h
	src/hook/menu_hook.cpp
	src/hook/menu_hook.h
	src/hook/player_hook.cpp
	src/hook/player_hook.h
	src/main.cpp
	src/papyrus/papyrus.cpp
	src/papyrus/papyrus.h
	src/processing/game_menu_setting.cpp
	src/processing/game_menu_setting.h
	src/processing/set_setting_data.cpp
	src/processing/set_setting_data.h
	src/processing/setting_execute.cpp
	src/processing/setting_execute.h
	src/setting/custom_setting.cpp
	src/setting/custom_setting.h
	src/setting/file_setting.cpp
	src/setting/file_setting.h
	src/setting/mcm_setting.cpp
	src/setting/mcm_setting.h
	src/ui/animation_handler.h
	src/ui/image_path.h
	src/ui/key_path.h
	src/ui/ui_renderer.cpp
	src/ui/ui_renderer.h
	src/util/constant.h
	src/util/data/config_writer_helper.h
	src/util/helper.cpp
	src/util/helper.h
	src/util/offset.h
	src/util/player/perk_visitor.cpp
	src/util/player/perk_visitor.h
	src/util/player/player.cpp
	src/util/player/player.h
	src/util/string_util.h
)
