#pragma once

// TODO autogenerate this in the justfile in the `sources` recipe

#include "animation_handler.h"
#include "config_writer_helper.h"
#include "constant.h"
#include "custom_setting.h"
#include "enums.h"
#include "file_setting.h"
#include "gear.h"
#include "helper.h"
#include "hooks.h"
#include "image_path.h"
#include "key_path.h"
#include "keycodes.h"
#include "magic.h"
#include "offset.h"
#include "papyrus.h"
#include "perk_visitor.h"
#include "player.h"
#include "sinks.h"
#include "string_util.h"
#include "ui_renderer.h"
#include "user_settings.h"
#include "utility_items.h"
#include "../plugin/handle/ammo_handle.h"
#include "../plugin/handle/data/ammo_data.h"
#include "../plugin/handle/data/page/position_draw_setting.h"
#include "../plugin/handle/data/page/position_setting.h"
#include "../plugin/handle/data/page/slot_setting.h"
#include "../plugin/handle/extra_data_holder.h"
#include "../plugin/handle/key_position_handle.h"
#include "../plugin/handle/name_handle.h"
#include "../plugin/handle/page_handle.h"
#include "../plugin/processing/game_menu_setting.h"
#include "../plugin/processing/set_setting_data.h"
#include "../plugin/processing/setting_execute.h"
