name: "Test the Rust code"
on:
    push:
        branches: ["latest"]
        paths:
            - src/**.rs
            - Cargo.toml
            - Cargo.lock
            - .github/workflows/test.yaml
    pull_request:
        branches: ["latest"]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            - name: get cargo-nextest on path
              run: |
                  curl -sL https://get.nexte.st/latest/linux -o nextest.tgz
                  tar xfz nextest.tgz
                  mv cargo-nextest /home/runner/.cargo/bin

            - name: verify that we have our data directory
              run: |
                  pwd
                  ls -alF data/SKSE/plugins/SoulsyHUD_Layout.toml
                  cargo --version

            - name: run the tests
              run: cargo nextest run
